# YAML Lint Configuration for Offensive Security Toolkit

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Document start
  document-start:
    present: false

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2

  # Comments
  comments:
    min-spaces-from-content: 1

  # Truthy values (allow yes/no in YAML)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
